import producer_server
from kafka import KafkaAdminClient
from kafka.admin import NewPartitions, NewTopic

def run_kafka_server():
	# TODO get the json file path
    input_file = "police-department-calls-for-service.json" # same folder as this script

    # TODO fill in blanks
    # GK Note: I have completed the code template provided by Udacity.
    # The provided code implies that the topic is autogenerated by KafkaProducer
    # The provided code doesn't call the Kafka AdminClient to create the topic explicitly
    # To experiment with number of Kafka partitions for performance, I create an admin client
    bootstrap_servers = 'localhost:9092'
    my_topic = "sf.police.calls"
    admin_client = KafkaAdminClient(bootstrap_servers=bootstrap_servers)
    try: 
        print("attempting to create new topic") 
        topic_list = [] 
        nb_partitions = 2
        topic_list.append(NewTopic(name= my_topic, num_partitions=nb_partitions, replication_factor=1)) 
        admin_client.create_topics(new_topics=topic_list, validate_only=False) 
    except Exception: 
        print("topic already exists")    
    
    producer = producer_server.ProducerServer(
    #producer = producer_server.ProducerServer(
        input_file=input_file,  # crime events file
        topic=my_topic, # freely chosen
        bootstrap_servers=bootstrap_servers,# standard choice for Kafka server
        client_id="producer-01" # ID chosen for this producer
    )
    return producer

def feed():
    producer = run_kafka_server()
    producer.generate_data()

if __name__ == "__main__":
    feed()
